DATA CLEANING & EDA

In [1]:
# import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# load the Data
df = pd.read_csv('E:/Project1/Credit Card Risk/Credit Card Fraud Risk Analysis.csv')

print("Number of Rows:",df.shape[0])
print("Number of Columns:",df.shape[1])
print(df.head())
print(df.info())
#check the missing value
print(df.isnull().sum())
#check the duplicate value
print(df.duplicated().sum())
#summary statistics of Numerical value
df.describe()

Number of Rows: 1000
Number of Columns: 14
   Transaction ID  Customer Name Merchant Name Transaction Date  \
0        17797619     Pihu Manne          Uber       2024-11-10
1        50040671   Hiran Vaidya        Zomato       2024-05-20
2        88177651     Shalv Vasa        Myntra       2024-05-28
3        24228305  Taran Shanker     Lifestyle       2024-01-09
4        87307869   Shanaya Kara     Tata Cliq       2024-07-27

   Transaction Amount (INR) Fraud Risk        Fraud Type          State  \
0                     11673     Medium  Card Not Present      Telangana
1                     16594     Medium          Phishing    Maharashtra
2                     23347     Medium     Card Skimming  Uttar Pradesh
3                     20753        Low     Card Skimming         Kerala
4                      6432        Low     Card Skimming          Delhi

  Card Type          Bank  IsFraud  Fraud Score Transaction Category  \
0     Rupay    ICICI Bank        0           57       Transportation
1      Amex           SBI        0           10            Groceries
2      Visa     HDFC Bank        0           55       Transportation
3      Visa  Federal Bank        0           30           E-commerce
4      Amex           SBI        0           86          Electronics

  Merchant Location
0         Bangalore
1         Bangalore
2         Ahmedabad
3           Lucknow
4         Hyderabad
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Transaction ID            1000 non-null   int64
 1   Customer Name             1000 non-null   object
 2   Merchant Name             1000 non-null   object
 3   Transaction Date          1000 non-null   object
 4   Transaction Amount (INR)  1000 non-null   int64
 5   Fraud Risk                1000 non-null   object
 6   Fraud Type                1000 non-null   object
 7   State                     1000 non-null   object
 8   Card Type                 1000 non-null   object
 9   Bank                      1000 non-null   object
 10  IsFraud                   1000 non-null   int64
 11  Fraud Score               1000 non-null   int64
 12  Transaction Category      1000 non-null   object
 13  Merchant Location         1000 non-null   object
dtypes: int64(4), object(10)
memory usage: 109.5+ KB
None
Transaction ID              0
Customer Name               0
Merchant Name               0
Transaction Date            0
Transaction Amount (INR)    0
Fraud Risk                  0
Fraud Type                  0
State                       0
Card Type                   0
Bank                        0
IsFraud                     0
Fraud Score                 0
Transaction Category        0
Merchant Location           0
dtype: int64
0

       Transaction ID  Transaction Amount (INR)      IsFraud  Fraud Score
count    1.000000e+03               1000.000000  1000.000000  1000.000000
mean     5.486023e+07              12226.843000     0.286000    53.179000
std      2.616482e+07               7106.084734     0.452115    25.723815
min      1.003645e+07                141.000000     0.000000    10.000000
25%      3.235345e+07               6218.000000     0.000000    29.000000
50%      5.379576e+07              11999.500000     0.000000    54.000000
75%      7.790521e+07              18207.750000     1.000000    76.000000
max      9.994398e+07              24993.000000     1.000000    95.000000

In [3]:
# Clean column Names
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
)

print(df.columns)
df

Index(['transaction_id', 'customer_name', 'merchant_name', 'transaction_date',
       'transaction_amount_inr', 'fraud_risk', 'fraud_type', 'state',
       'card_type', 'bank', 'isfraud', 'fraud_score', 'transaction_category',
       'merchant_location'],
      dtype='object')

,transaction_id,customer_name,merchant_name,transaction_date,transaction_amount_inr,fraud_risk,fraud_type,state,card_type,bank,isfraud,fraud_score,transaction_category,merchant_location
0,17797619,Pihu Manne,Uber,2024-11-10,11673,Medium,Card Not Present,Telangana,Rupay,ICICI Bank,0,57,Transportation,Bangalore
1,50040671,Hiran Vaidya,Zomato,2024-05-20,16594,Medium,Phishing,Maharashtra,Amex,SBI,0,10,Groceries,Bangalore
2,88177651,Shalv Vasa,Myntra,2024-05-28,23347,Medium,Card Skimming,Uttar Pradesh,Visa,HDFC Bank,0,55,Transportation,Ahmedabad
3,24228305,Taran Shanker,Lifestyle,2024-01-09,20753,Low,Card Skimming,Kerala,Visa,Federal Bank,0,30,E-commerce,Lucknow
4,87307869,Shanaya Kara,Tata Cliq,2024-07-27,6432,Low,Card Skimming,Delhi,Amex,SBI,0,86,Electronics,Hyderabad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,97151229,Nitya Ganesh,Flipkart,2024-05-09,2834,Medium,Account Takeover,Rajasthan,Visa,SBI,0,14,Apparel,Lucknow
996,46529985,Shray Dubey,Lifestyle,2024-10-02,12740,Low,Phishing,Maharashtra,Amex,Bank of Baroda,0,16,Electronics,Chennai
997,10160858,Kaira Kumar,Tata Cliq,2024-11-21,20057,Critical,Phishing,West Bengal,Amex,ICICI Bank,0,43,Food Delivery,Hyderabad
998,48484987,Rati Date,Lifestyle,2024-08-30,19933,High,Account Takeover,Kerala,Amex,Andhra Bank,1,16,Transportation,Hyderabad
999,20156336,Baiju Dubey,Uber,2024-05-07,17105,Medium,Phishing,Maharashtra,Visa,HDFC Bank,0,82,Groceries,Mumbai

In [4]:
#check data types
print(df.dtypes)

transaction_id             int64
customer_name             object
merchant_name             object
transaction_date          object
transaction_amount_inr     int64
fraud_risk                object
fraud_type                object
state                     object
card_type                 object
bank                      object
isfraud                    int64
fraud_score                int64
transaction_category      object
merchant_location         object
dtype: object

In [5]:
# Convert Date Columns
df["transaction_date"] = pd.to_datetime(df["transaction_date"])
df
print(df.dtypes)

transaction_id                     int64
customer_name                     object
merchant_name                     object
transaction_date          datetime64[ns]
transaction_amount_inr             int64
fraud_risk                        object
fraud_type                        object
state                             object
card_type                         object
bank                              object
isfraud                            int64
fraud_score                        int64
transaction_category              object
merchant_location                 object
dtype: object

In [6]:
#create date features
df["year"] = df["transaction_date"].dt.year
df["month_no"] = df["transaction_date"].dt.month
df["month_name"] = df["transaction_date"].dt.month_name()
df["quarter"] = df["transaction_date"].dt.quarter
df["day_name"] = df["transaction_date"].dt.day_name()
df["month_year"] = df["transaction_date"].dt.to_period("M").astype(str)
df

,transaction_id,customer_name,merchant_name,transaction_date,transaction_amount_inr,fraud_risk,fraud_type,state,card_type,bank,isfraud,fraud_score,transaction_category,merchant_location,year,month_no,month_name,quarter,day_name,month_year
0,17797619,Pihu Manne,Uber,2024-11-10,11673,Medium,Card Not Present,Telangana,Rupay,ICICI Bank,0,57,Transportation,Bangalore,2024,11,November,4,Sunday,2024-11
1,50040671,Hiran Vaidya,Zomato,2024-05-20,16594,Medium,Phishing,Maharashtra,Amex,SBI,0,10,Groceries,Bangalore,2024,5,May,2,Monday,2024-05
2,88177651,Shalv Vasa,Myntra,2024-05-28,23347,Medium,Card Skimming,Uttar Pradesh,Visa,HDFC Bank,0,55,Transportation,Ahmedabad,2024,5,May,2,Tuesday,2024-05
3,24228305,Taran Shanker,Lifestyle,2024-01-09,20753,Low,Card Skimming,Kerala,Visa,Federal Bank,0,30,E-commerce,Lucknow,2024,1,January,1,Tuesday,2024-01
4,87307869,Shanaya Kara,Tata Cliq,2024-07-27,6432,Low,Card Skimming,Delhi,Amex,SBI,0,86,Electronics,Hyderabad,2024,7,July,3,Saturday,2024-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,97151229,Nitya Ganesh,Flipkart,2024-05-09,2834,Medium,Account Takeover,Rajasthan,Visa,SBI,0,14,Apparel,Lucknow,2024,5,May,2,Thursday,2024-05
996,46529985,Shray Dubey,Lifestyle,2024-10-02,12740,Low,Phishing,Maharashtra,Amex,Bank of Baroda,0,16,Electronics,Chennai,2024,10,October,4,Wednesday,2024-10
997,10160858,Kaira Kumar,Tata Cliq,2024-11-21,20057,Critical,Phishing,West Bengal,Amex,ICICI Bank,0,43,Food Delivery,Hyderabad,2024,11,November,4,Thursday,2024-11
998,48484987,Rati Date,Lifestyle,2024-08-30,19933,High,Account Takeover,Kerala,Amex,Andhra Bank,1,16,Transportation,Hyderabad,2024,8,August,3,Friday,2024-08
999,20156336,Baiju Dubey,Uber,2024-05-07,17105,Medium,Phishing,Maharashtra,Visa,HDFC Bank,0,82,Groceries,Mumbai,2024,5,May,2,Tuesday,2024-05

In [7]:
#clean fraud type
df["fraud_type_clean"] = np.where(
    df["isfraud"] == 1,
    df["fraud_type"],
    "Not Fraud"
)
df

,transaction_id,customer_name,merchant_name,transaction_date,transaction_amount_inr,fraud_risk,fraud_type,state,card_type,bank,...,fraud_score,transaction_category,merchant_location,year,month_no,month_name,quarter,day_name,month_year,fraud_type_clean
0,17797619,Pihu Manne,Uber,2024-11-10,11673,Medium,Card Not Present,Telangana,Rupay,ICICI Bank,...,57,Transportation,Bangalore,2024,11,November,4,Sunday,2024-11,Not Fraud
1,50040671,Hiran Vaidya,Zomato,2024-05-20,16594,Medium,Phishing,Maharashtra,Amex,SBI,...,10,Groceries,Bangalore,2024,5,May,2,Monday,2024-05,Not Fraud
2,88177651,Shalv Vasa,Myntra,2024-05-28,23347,Medium,Card Skimming,Uttar Pradesh,Visa,HDFC Bank,...,55,Transportation,Ahmedabad,2024,5,May,2,Tuesday,2024-05,Not Fraud
3,24228305,Taran Shanker,Lifestyle,2024-01-09,20753,Low,Card Skimming,Kerala,Visa,Federal Bank,...,30,E-commerce,Lucknow,2024,1,January,1,Tuesday,2024-01,Not Fraud
4,87307869,Shanaya Kara,Tata Cliq,2024-07-27,6432,Low,Card Skimming,Delhi,Amex,SBI,...,86,Electronics,Hyderabad,2024,7,July,3,Saturday,2024-07,Not Fraud
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,97151229,Nitya Ganesh,Flipkart,2024-05-09,2834,Medium,Account Takeover,Rajasthan,Visa,SBI,...,14,Apparel,Lucknow,2024,5,May,2,Thursday,2024-05,Not Fraud
996,46529985,Shray Dubey,Lifestyle,2024-10-02,12740,Low,Phishing,Maharashtra,Amex,Bank of Baroda,...,16,Electronics,Chennai,2024,10,October,4,Wednesday,2024-10,Not Fraud
997,10160858,Kaira Kumar,Tata Cliq,2024-11-21,20057,Critical,Phishing,West Bengal,Amex,ICICI Bank,...,43,Food Delivery,Hyderabad,2024,11,November,4,Thursday,2024-11,Not Fraud
998,48484987,Rati Date,Lifestyle,2024-08-30,19933,High,Account Takeover,Kerala,Amex,Andhra Bank,...,16,Transportation,Hyderabad,2024,8,August,3,Friday,2024-08,Account Takeover
999,20156336,Baiju Dubey,Uber,2024-05-07,17105,Medium,Phishing,Maharashtra,Visa,HDFC Bank,...,82,Groceries,Mumbai,2024,5,May,2,Tuesday,2024-05,Not Fraud

In [8]:
#create amount bucket
df["amount_bucket"] = pd.cut(
    df["transaction_amount_inr"],
    bins=[0, 5000, 10000, 15000, 20000, 25000],
    labels=["0-5K", "5K-10K", "10K-15K", "15K-20K", "20K-25K"]
)
df

,transaction_id,customer_name,merchant_name,transaction_date,transaction_amount_inr,fraud_risk,fraud_type,state,card_type,bank,...,transaction_category,merchant_location,year,month_no,month_name,quarter,day_name,month_year,fraud_type_clean,amount_bucket
0,17797619,Pihu Manne,Uber,2024-11-10,11673,Medium,Card Not Present,Telangana,Rupay,ICICI Bank,...,Transportation,Bangalore,2024,11,November,4,Sunday,2024-11,Not Fraud,10K-15K
1,50040671,Hiran Vaidya,Zomato,2024-05-20,16594,Medium,Phishing,Maharashtra,Amex,SBI,...,Groceries,Bangalore,2024,5,May,2,Monday,2024-05,Not Fraud,15K-20K
2,88177651,Shalv Vasa,Myntra,2024-05-28,23347,Medium,Card Skimming,Uttar Pradesh,Visa,HDFC Bank,...,Transportation,Ahmedabad,2024,5,May,2,Tuesday,2024-05,Not Fraud,20K-25K
3,24228305,Taran Shanker,Lifestyle,2024-01-09,20753,Low,Card Skimming,Kerala,Visa,Federal Bank,...,E-commerce,Lucknow,2024,1,January,1,Tuesday,2024-01,Not Fraud,20K-25K
4,87307869,Shanaya Kara,Tata Cliq,2024-07-27,6432,Low,Card Skimming,Delhi,Amex,SBI,...,Electronics,Hyderabad,2024,7,July,3,Saturday,2024-07,Not Fraud,5K-10K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,97151229,Nitya Ganesh,Flipkart,2024-05-09,2834,Medium,Account Takeover,Rajasthan,Visa,SBI,...,Apparel,Lucknow,2024,5,May,2,Thursday,2024-05,Not Fraud,0-5K
996,46529985,Shray Dubey,Lifestyle,2024-10-02,12740,Low,Phishing,Maharashtra,Amex,Bank of Baroda,...,Electronics,Chennai,2024,10,October,4,Wednesday,2024-10,Not Fraud,10K-15K
997,10160858,Kaira Kumar,Tata Cliq,2024-11-21,20057,Critical,Phishing,West Bengal,Amex,ICICI Bank,...,Food Delivery,Hyderabad,2024,11,November,4,Thursday,2024-11,Not Fraud,20K-25K
998,48484987,Rati Date,Lifestyle,2024-08-30,19933,High,Account Takeover,Kerala,Amex,Andhra Bank,...,Transportation,Hyderabad,2024,8,August,3,Friday,2024-08,Account Takeover,15K-20K
999,20156336,Baiju Dubey,Uber,2024-05-07,17105,Medium,Phishing,Maharashtra,Visa,HDFC Bank,...,Groceries,Mumbai,2024,5,May,2,Tuesday,2024-05,Not Fraud,15K-20K

In [9]:
#create fraud score bucket
df["fraud_score_bucket"] = pd.cut(
    df["fraud_score"],
    bins=[0, 25, 50, 75, 100],
    labels=["Low Score", "Medium Score", "High Score", "Very High Score"]
)
df

,transaction_id,customer_name,merchant_name,transaction_date,transaction_amount_inr,fraud_risk,fraud_type,state,card_type,bank,...,merchant_location,year,month_no,month_name,quarter,day_name,month_year,fraud_type_clean,amount_bucket,fraud_score_bucket
0,17797619,Pihu Manne,Uber,2024-11-10,11673,Medium,Card Not Present,Telangana,Rupay,ICICI Bank,...,Bangalore,2024,11,November,4,Sunday,2024-11,Not Fraud,10K-15K,High Score
1,50040671,Hiran Vaidya,Zomato,2024-05-20,16594,Medium,Phishing,Maharashtra,Amex,SBI,...,Bangalore,2024,5,May,2,Monday,2024-05,Not Fraud,15K-20K,Low Score
2,88177651,Shalv Vasa,Myntra,2024-05-28,23347,Medium,Card Skimming,Uttar Pradesh,Visa,HDFC Bank,...,Ahmedabad,2024,5,May,2,Tuesday,2024-05,Not Fraud,20K-25K,High Score
3,24228305,Taran Shanker,Lifestyle,2024-01-09,20753,Low,Card Skimming,Kerala,Visa,Federal Bank,...,Lucknow,2024,1,January,1,Tuesday,2024-01,Not Fraud,20K-25K,Medium Score
4,87307869,Shanaya Kara,Tata Cliq,2024-07-27,6432,Low,Card Skimming,Delhi,Amex,SBI,...,Hyderabad,2024,7,July,3,Saturday,2024-07,Not Fraud,5K-10K,Very High Score
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,97151229,Nitya Ganesh,Flipkart,2024-05-09,2834,Medium,Account Takeover,Rajasthan,Visa,SBI,...,Lucknow,2024,5,May,2,Thursday,2024-05,Not Fraud,0-5K,Low Score
996,46529985,Shray Dubey,Lifestyle,2024-10-02,12740,Low,Phishing,Maharashtra,Amex,Bank of Baroda,...,Chennai,2024,10,October,4,Wednesday,2024-10,Not Fraud,10K-15K,Low Score
997,10160858,Kaira Kumar,Tata Cliq,2024-11-21,20057,Critical,Phishing,West Bengal,Amex,ICICI Bank,...,Hyderabad,2024,11,November,4,Thursday,2024-11,Not Fraud,20K-25K,Medium Score
998,48484987,Rati Date,Lifestyle,2024-08-30,19933,High,Account Takeover,Kerala,Amex,Andhra Bank,...,Hyderabad,2024,8,August,3,Friday,2024-08,Account Takeover,15K-20K,Low Score
999,20156336,Baiju Dubey,Uber,2024-05-07,17105,Medium,Phishing,Maharashtra,Visa,HDFC Bank,...,Mumbai,2024,5,May,2,Tuesday,2024-05,Not Fraud,15K-20K,Very High Score

In [10]:
#Risk rank
risk_map = {
    "Low": 1,
    "Medium": 2,
    "High": 3,
    "Critical": 4
}

df["risk_rank"] = df["fraud_risk"].map(risk_map)
df

,transaction_id,customer_name,merchant_name,transaction_date,transaction_amount_inr,fraud_risk,fraud_type,state,card_type,bank,...,year,month_no,month_name,quarter,day_name,month_year,fraud_type_clean,amount_bucket,fraud_score_bucket,risk_rank
0,17797619,Pihu Manne,Uber,2024-11-10,11673,Medium,Card Not Present,Telangana,Rupay,ICICI Bank,...,2024,11,November,4,Sunday,2024-11,Not Fraud,10K-15K,High Score,2
1,50040671,Hiran Vaidya,Zomato,2024-05-20,16594,Medium,Phishing,Maharashtra,Amex,SBI,...,2024,5,May,2,Monday,2024-05,Not Fraud,15K-20K,Low Score,2
2,88177651,Shalv Vasa,Myntra,2024-05-28,23347,Medium,Card Skimming,Uttar Pradesh,Visa,HDFC Bank,...,2024,5,May,2,Tuesday,2024-05,Not Fraud,20K-25K,High Score,2
3,24228305,Taran Shanker,Lifestyle,2024-01-09,20753,Low,Card Skimming,Kerala,Visa,Federal Bank,...,2024,1,January,1,Tuesday,2024-01,Not Fraud,20K-25K,Medium Score,1
4,87307869,Shanaya Kara,Tata Cliq,2024-07-27,6432,Low,Card Skimming,Delhi,Amex,SBI,...,2024,7,July,3,Saturday,2024-07,Not Fraud,5K-10K,Very High Score,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,97151229,Nitya Ganesh,Flipkart,2024-05-09,2834,Medium,Account Takeover,Rajasthan,Visa,SBI,...,2024,5,May,2,Thursday,2024-05,Not Fraud,0-5K,Low Score,2
996,46529985,Shray Dubey,Lifestyle,2024-10-02,12740,Low,Phishing,Maharashtra,Amex,Bank of Baroda,...,2024,10,October,4,Wednesday,2024-10,Not Fraud,10K-15K,Low Score,1
997,10160858,Kaira Kumar,Tata Cliq,2024-11-21,20057,Critical,Phishing,West Bengal,Amex,ICICI Bank,...,2024,11,November,4,Thursday,2024-11,Not Fraud,20K-25K,Medium Score,4
998,48484987,Rati Date,Lifestyle,2024-08-30,19933,High,Account Takeover,Kerala,Amex,Andhra Bank,...,2024,8,August,3,Friday,2024-08,Account Takeover,15K-20K,Low Score,3
999,20156336,Baiju Dubey,Uber,2024-05-07,17105,Medium,Phishing,Maharashtra,Visa,HDFC Bank,...,2024,5,May,2,Tuesday,2024-05,Not Fraud,15K-20K,Very High Score,2

In [11]:
#KPI Calculation
total_transactions = df["transaction_id"].count()
fraud_transactions = df["isfraud"].sum()
fraud_rate = fraud_transactions / total_transactions
total_amount = df["transaction_amount_inr"].sum()
fraud_amount = df.loc[df["isfraud"] == 1, "transaction_amount_inr"].sum()

print("Total Transactions:", total_transactions)
print("Fraud Transactions:", fraud_transactions)
print("Fraud Rate:", round(fraud_rate * 100, 2), "%")
print("Total Amount:", total_amount)
print("Fraud Amount:", fraud_amount)

Total Transactions: 1000
Fraud Transactions: 286
Fraud Rate: 28.6 %
Total Amount: 12226843
Fraud Amount: 3306813

EDA ANALYSIS

In [12]:
#Fraud by Category
category_fraud = df.groupby("transaction_category").agg(
    total_transactions=("transaction_id", "count"),
    fraud_transactions=("isfraud", "sum"),
    total_amount=("transaction_amount_inr", "sum")
)

category_fraud["fraud_rate"] = (
    category_fraud["fraud_transactions"] / category_fraud["total_transactions"] * 100
)

category_fraud.sort_values("fraud_rate", ascending=False)

,total_transactions,fraud_transactions,total_amount,fraud_rate
transaction_category,,,,
Food Delivery,148,48,1804118,32.432432
E-commerce,174,54,2125395,31.034483
Electronics,179,54,1993079,30.167598
Apparel,162,44,2014873,27.160494
Groceries,154,41,1877974,26.623377
Transportation,183,45,2411404,24.590164

In [13]:
#Fraud by State
state_fraud = df.groupby("state").agg(
    total_transactions=("transaction_id", "count"),
    fraud_transactions=("isfraud", "sum")
)

state_fraud["fraud_rate"] = (
    state_fraud["fraud_transactions"] / state_fraud["total_transactions"] * 100
)

state_fraud.sort_values("fraud_rate", ascending=False)

               total_transactions  fraud_transactions  fraud_rate
state
Karnataka                      96                  34   35.416667
Maharashtra                   107                  36   33.644860
West Bengal                   104                  33   31.730769
Rajasthan                     113                  34   30.088496
Uttar Pradesh                 100                  29   29.000000
Telangana                      98                  27   27.551020
Tamil Nadu                    102                  28   27.450980
Gujarat                        94                  23   24.468085
Delhi                          92                  21   22.826087
Kerala                         94                  21   22.340426

In [14]:
#Fraud by Card Type
card_fraud = df.groupby("card_type").agg(
    total_transactions=("transaction_id", "count"),
    fraud_transactions=("isfraud", "sum")
)

card_fraud["fraud_rate"] = (
    card_fraud["fraud_transactions"] / card_fraud["total_transactions"] * 100
)

card_fraud.sort_values("fraud_rate", ascending=False)

            total_transactions  fraud_transactions  fraud_rate
card_type
Visa                       261                  88   33.716475
Mastercard                 237                  66   27.848101
Amex                       255                  71   27.843137
Rupay                      247                  61   24.696356

In [15]:
#saved the clean file
df.to_csv("clean_credit_card_fraud_analysis.csv", index=False)

SQL SERVER WORKFLOW

In [16]:
#create connection for sql server
import pyodbc
server = "DESKTOP-BND2C7N"   
database = "Fraud_Analysis"            

conn = pyodbc.connect(
    f"DRIVER={{ODBC Driver 18 for SQL Server}};"
    f"SERVER={server};"
    f"DATABASE={database};"
    f"Trusted_Connection=yes;"
    f"TrustServerCertificate=yes;"
)

print("Connected successfully")

Connected successfully

In [17]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

server = "DESKTOP-BND2C7N"   
database = "Fraud_Analysis"            

connection_string = quote_plus(
    f"DRIVER={{ODBC Driver 18 for SQL Server}};"
    f"SERVER={server};"
    f"DATABASE={database};"
    f"Trusted_Connection=yes;"
    f"TrustServerCertificate=yes;"
)

engine = create_engine(f"mssql+pyodbc:///?odbc_connect={connection_string}")

In [18]:
df.to_sql(
    name="clean_credit_card_fraud_analysis",
    con=engine,
    schema="dbo",
    if_exists="replace",
    index=False
)

-1

In [19]:
check_df = pd.read_sql(
    "SELECT TOP 10 * FROM dbo.clean_credit_card_fraud_analysis",
    con=engine
)

check_df.head()

,transaction_id,customer_name,merchant_name,transaction_date,transaction_amount_inr,fraud_risk,fraud_type,state,card_type,bank,...,year,month_no,month_name,quarter,day_name,month_year,fraud_type_clean,amount_bucket,fraud_score_bucket,risk_rank
0,17797619,Pihu Manne,Uber,2024-11-10,11673,Medium,Card Not Present,Telangana,Rupay,ICICI Bank,...,2024,11,November,4,Sunday,2024-11,Not Fraud,10K-15K,High Score,2
1,50040671,Hiran Vaidya,Zomato,2024-05-20,16594,Medium,Phishing,Maharashtra,Amex,SBI,...,2024,5,May,2,Monday,2024-05,Not Fraud,15K-20K,Low Score,2
2,88177651,Shalv Vasa,Myntra,2024-05-28,23347,Medium,Card Skimming,Uttar Pradesh,Visa,HDFC Bank,...,2024,5,May,2,Tuesday,2024-05,Not Fraud,20K-25K,High Score,2
3,24228305,Taran Shanker,Lifestyle,2024-01-09,20753,Low,Card Skimming,Kerala,Visa,Federal Bank,...,2024,1,January,1,Tuesday,2024-01,Not Fraud,20K-25K,Medium Score,1
4,87307869,Shanaya Kara,Tata Cliq,2024-07-27,6432,Low,Card Skimming,Delhi,Amex,SBI,...,2024,7,July,3,Saturday,2024-07,Not Fraud,5K-10K,Very High Score,1

In [23]:
# 1. Overall KPI 
check_df = pd.read_sql("""select count(*) total_transactions,sum(case when isfraud = 1 then 1 else 0 end) fraud_transactions,cast
                        (sum(case when isfraud = 1 then 1 else 0 end) * 100.0 / count(*) as decimal(10,2)) fraud_rate_percentage,
                        sum(transaction_amount_inr) total_transaction_amount, sum(case when isfraud = 1 then transaction_amount_inr else 0 
                        end) fraud_transaction_amount, avg(cast(fraud_score as float)) avg_fraud_score
                        from dbo.clean_credit_card_fraud_analysis""", con=engine)
check_df

,total_transactions,fraud_transactions,fraud_rate_percentage,total_transaction_amount,fraud_transaction_amount,avg_fraud_score
0,1000,286,28.6,12226843,3306813,53.179

In [26]:
# 2. Fraud by Transaction Category
check_df = pd.read_sql("""select transaction_category,count(*) total_transactions,sum(case when isfraud = 1 then 1 else 0 end) 
                        fraud_transactions,cast(sum(case when isfraud = 1 then 1 else 0 end) * 100.0 / count(*) as decimal(10,2))
                        fraud_rate_percentage,sum(transaction_amount_inr) total_amount
                        from dbo.clean_credit_card_fraud_analysis
                        group by transaction_category
                        order by fraud_rate_percentage DESC;""",con = engine)
check_df

,transaction_category,total_transactions,fraud_transactions,fraud_rate_percentage,total_amount
0,Food Delivery,148,48,32.43,1804118
1,E-commerce,174,54,31.03,2125395
2,Electronics,179,54,30.17,1993079
3,Apparel,162,44,27.16,2014873
4,Groceries,154,41,26.62,1877974
5,Transportation,183,45,24.59,2411404

In [27]:
# 3. Fraud by State
check_df = pd.read_sql("""select state,count(*) total_transactions,sum(case when isfraud = 1 then 1 else 0 end) 
                        fraud_transactions,cast(sum(case when isfraud = 1 then 1 else 0 end) * 100.0 / count(*) as decimal(10,2))
                        fraud_rate_percentage,sum(transaction_amount_inr) total_amount
                        from dbo.clean_credit_card_fraud_analysis
                        group by state
                        order by fraud_rate_percentage DESC;""",con = engine)
check_df

,state,total_transactions,fraud_transactions,fraud_rate_percentage,total_amount
0,Karnataka,96,34,35.42,1304595
1,Maharashtra,107,36,33.64,1245027
2,West Bengal,104,33,31.73,1381155
3,Rajasthan,113,34,30.09,1309890
4,Uttar Pradesh,100,29,29.00,1308323
5,Telangana,98,27,27.55,1096363
6,Tamil Nadu,102,28,27.45,1155314
7,Gujarat,94,23,24.47,1180026
8,Delhi,92,21,22.83,1091273
9,Kerala,94,21,22.34,1154877

In [29]:
# 4. Monthly Fraud Trend
check_df = pd.read_sql("""select year,month_no,month_name,count(*) total_transactions,
                        sum(case when isfraud = 1 then 1 else 0 end) fraud_transactions,cast(sum(case when isfraud = 1 then 1 else 0 end) 
                        * 100.0 / count(*) as decimal(10,2)) fraud_rate_percentage,sum(transaction_amount_inr) total_amount,
                        sum(case when isfraud = 1 then transaction_amount_inr else 0 end) fraud_amount
                        from dbo.clean_credit_card_fraud_analysis
                        group by year, month_no, month_name
                        order by year, month_no""",con = engine)
check_df

,year,month_no,month_name,total_transactions,fraud_transactions,fraud_rate_percentage,total_amount,fraud_amount
0,2023,12,December,51,15,29.41,586503,118082
1,2024,1,January,78,17,21.79,986019,208279
2,2024,2,February,83,18,21.69,882903,197407
3,2024,3,March,89,26,29.21,1090851,268095
4,2024,4,April,77,22,28.57,991622,252797
5,2024,5,May,94,22,23.40,1125317,252826
6,2024,6,June,75,28,37.33,952807,376372
7,2024,7,July,86,26,30.23,1058071,334948
8,2024,8,August,79,29,36.71,1033667,370565
9,2024,9,September,61,21,34.43,625421,135941
10,2024,10,October,93,22,23.66,1163626,253391
11,2024,11,November,84,21,25.00,1038888,301822
12,2024,12,December,50,19,38.00,691148,236288

In [30]:
# 5. Top Risky Merchant
check_df = pd.read_sql("""select merchant_name,count(*) total_transactions,sum(case when isfraud = 1 then 1 else 0 end) 
                        fraud_transactions,cast(sum(case when isfraud = 1 then 1 else 0 end) * 100.0 / count(*) as decimal(10,2))
                        fraud_rate_percentage,sum(transaction_amount_inr) total_amount
                        from dbo.clean_credit_card_fraud_analysis
                        group by merchant_name
                        order by fraud_rate_percentage DESC;""",con = engine)
check_df

,merchant_name,total_transactions,fraud_transactions,fraud_rate_percentage,total_amount
0,Zomato,107,37,34.58,1299362
1,Big Bazaar,105,35,33.33,1223781
2,Reliance Digital,92,29,31.52,1165376
3,Tata Cliq,96,30,31.25,1190481
4,Flipkart,97,28,28.87,1049914
5,Myntra,108,31,28.70,1246292
6,Uber,96,26,27.08,1194634
7,Amazon India,84,22,26.19,1037209
8,Swiggy,94,24,25.53,1190125
9,Lifestyle,121,24,19.83,1629669

In [31]:
# Fraud by Bank
check_df = pd.read_sql("""select bank,count(*) total_transactions,sum(case when isfraud = 1 then 1 else 0 end) 
                        fraud_transactions,cast(sum(case when isfraud = 1 then 1 else 0 end) * 100.0 / count(*) as decimal(10,2))
                        fraud_rate_percentage,sum(transaction_amount_inr) total_amount
                        from dbo.clean_credit_card_fraud_analysis
                        group by bank
                        order by fraud_rate_percentage DESC;""",con = engine)
check_df

,bank,total_transactions,fraud_transactions,fraud_rate_percentage,total_amount
0,Andhra Bank,118,41,34.75,1396814
1,HDFC Bank,104,33,31.73,1217266
2,Kotak Bank,110,32,29.09,1360052
3,ICICI Bank,126,36,28.57,1629125
4,Axis Bank,105,29,27.62,1275435
5,SBI,103,28,27.18,1317987
6,Bank of Baroda,106,28,26.42,1140892
7,Federal Bank,106,28,26.42,1411039
8,Yes Bank,122,31,25.41,1478233